services:
  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smeshtaj_dan_trebit
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: ppaunovski/backend
    networks:
      - backend
      - frontend
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smeshtaj_dan_trebit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - API_HOST=localhost
    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    image: ppaunovski/frontend:latest
    networks:
      - backend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  postgres:
    driver: bridge