apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: smeshtaj
  name: postgres-pv
  labels:
    type: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
