name: Super Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
#  lint:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        folder: [Frontend, Backend]
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          # Full git history is needed to get a proper list of changed files within `super-linter`
#          fetch-depth: 0
#
#      - name: Run Super Linter
#        uses: github/super-linter@v4
#        env:
#          DEFAULT_BRANCH: "master"
#          VALIDATE_JS: true
#          VALIDATE_TS: true
#          VALIDATE_HTML: true
#          VALIDATE_CSS: true
#          VALIDATE_KOTLIN: true
#          FILES_TO_LINT: ${{ matrix.folder }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.5'

      - name: Grant execute permission for gradlew
        run: chmod +x ./Backend/gradlew

      - name: Build with Gradle
        run: ./Backend/gradlew clean build -x test

  build-and-push:
    runs-on: ubuntu-latest
    needs: build

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest -f backend.dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -f frontend.dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
